
import java.util.ArrayList;
import java.util.Date;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class Principa extends javax.swing.JFrame {

    int contl = 0;
    int usuario;
    String administ = "Admin";
    String passwr = "Honduras";
    String user;
    String password;
    ArrayList<Usuario> lista = new ArrayList();
    ArrayList<Libro> libro = new ArrayList();
    Usuario c;

    /**
     * Creates new form Principa
     */
    public Principa() {

        initComponents();
        Usuario.setEnabled(false);
        Ingresar.setEnabled(false);
        Modificar.setEnabled(false);
        Modificar.setVisible(false);
        Usuario.setVisible(false);
        Ingresar.setVisible(false);
        modif.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rgb_genero = new javax.swing.ButtonGroup();
        rgb_genero1 = new javax.swing.ButtonGroup();
        rgb_puntaje = new javax.swing.ButtonGroup();
        genero = new javax.swing.ButtonGroup();
        puntae = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Modifica = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pf_contrase = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        pf_contraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        tf_numero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rb_fantasia = new javax.swing.JRadioButton();
        rb_romance = new javax.swing.JRadioButton();
        rb_accion = new javax.swing.JRadioButton();
        rb_historia = new javax.swing.JRadioButton();
        bt_crear = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Usuario = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        informacion = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        Agregar_amigo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_suger = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        Devolver = new javax.swing.JComboBox<>();
        Agregar_libro = new javax.swing.JComboBox<>();
        Modificar = new javax.swing.JPanel();
        Modificar_libro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        modif = new javax.swing.JPanel();
        dc_fecha2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        tf_copias1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_titulo1 = new javax.swing.JTextField();
        rb_fantasia2 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        rb_romance2 = new javax.swing.JRadioButton();
        rb_accion2 = new javax.swing.JRadioButton();
        rb_historia2 = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        tf_descripcion1 = new javax.swing.JTextField();
        tf_valor1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rb_6 = new javax.swing.JRadioButton();
        tf_edicion1 = new javax.swing.JTextField();
        rb_7 = new javax.swing.JRadioButton();
        tf_autor1 = new javax.swing.JTextField();
        rb_8 = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        rb_9 = new javax.swing.JRadioButton();
        jLabel29 = new javax.swing.JLabel();
        rb_10 = new javax.swing.JRadioButton();
        Mofidica = new javax.swing.JButton();
        Ingresar = new javax.swing.JPanel();
        dc_fecha1 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tf_copias = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        rb_fantasia1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rb_romance1 = new javax.swing.JRadioButton();
        rb_accion1 = new javax.swing.JRadioButton();
        rb_historia1 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        tf_descripcion = new javax.swing.JTextField();
        tf_valor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rb_1 = new javax.swing.JRadioButton();
        tf_edicion = new javax.swing.JTextField();
        rb_2 = new javax.swing.JRadioButton();
        tf_autor = new javax.swing.JTextField();
        rb_3 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rb_4 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        rb_5 = new javax.swing.JRadioButton();
        Borra = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Username");

        jLabel1.setText("Contraseña");

        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_user)
                            .addComponent(pf_contrase, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_contrase, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        Modifica.addTab("Login", jPanel6);

        jLabel2.setText("Usuario");

        jLabel5.setText("Contraseña");

        pf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_contraseñaActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha de nacimiento");

        jLabel4.setText("Numero telefonico");

        jLabel7.setText("Email");

        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre Completo");

        jLabel9.setText("Genero favorito");

        rgb_genero.add(rb_fantasia);
        rb_fantasia.setText("Fantasia");

        rgb_genero.add(rb_romance);
        rb_romance.setText("Romance");

        rgb_genero.add(rb_accion);
        rb_accion.setText("Accion");

        rgb_genero.add(rb_historia);
        rb_historia.setText("Historia");

        bt_crear.setText("Crear");
        bt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tf_numero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_contraseña, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rb_fantasia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_romance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_accion))
                            .addComponent(tf_email, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_historia)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb_fantasia)
                    .addComponent(rb_romance)
                    .addComponent(rb_accion)
                    .addComponent(rb_historia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(bt_crear))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Modifica.addTab("Crear", jPanel7);

        jButton2.setText("Agregar Libro");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Devolver Libro");

        jButton4.setText("Informacion de un libro especifico");

        informacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton5.setText("Agregar amigo");

        Agregar_amigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jl_suger.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jl_suger);

        jLabel10.setText("Sugerencias");

        Agregar_libro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout UsuarioLayout = new javax.swing.GroupLayout(Usuario);
        Usuario.setLayout(UsuarioLayout);
        UsuarioLayout.setHorizontalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(informacion, 0, 162, Short.MAX_VALUE)
                            .addComponent(Agregar_amigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Devolver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Agregar_libro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        UsuarioLayout.setVerticalGroup(
            UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(Agregar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(Agregar_amigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Modifica.addTab("Usuario", jPanel8);

        jLabel11.setText("Escoja el libro a modificar");

        jLabel21.setText("Numero de copias");

        tf_copias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_copias1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Titulo");

        jLabel23.setText("Genero");

        tf_titulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_titulo1ActionPerformed(evt);
            }
        });

        rgb_genero1.add(rb_fantasia2);
        rb_fantasia2.setText("Fantasia");

        jLabel24.setText("Descripcion");

        rgb_genero1.add(rb_romance2);
        rb_romance2.setText("Romance");

        rgb_genero1.add(rb_accion2);
        rb_accion2.setText("Accion");

        rgb_genero1.add(rb_historia2);
        rb_historia2.setText("Historia");

        jLabel25.setText("Valor");

        jLabel26.setText("Puntaje");

        jLabel27.setText("Edicion");

        puntae.add(rb_6);
        rb_6.setText("1");

        tf_edicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_edicion1ActionPerformed(evt);
            }
        });

        puntae.add(rb_7);
        rb_7.setText("2");

        puntae.add(rb_8);
        rb_8.setText("3");

        jLabel28.setText("Autor");

        puntae.add(rb_9);
        rb_9.setText("4");

        jLabel29.setText("Fecha de publicacion");

        puntae.add(rb_10);
        rb_10.setText("5");

        javax.swing.GroupLayout modifLayout = new javax.swing.GroupLayout(modif);
        modif.setLayout(modifLayout);
        modifLayout.setHorizontalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifLayout.createSequentialGroup()
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_titulo1)
                            .addComponent(tf_descripcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(modifLayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_10))
                    .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifLayout.createSequentialGroup()
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tf_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifLayout.createSequentialGroup()
                            .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_autor1)
                                .addComponent(tf_edicion1))))
                    .addGroup(modifLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(modifLayout.createSequentialGroup()
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(modifLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(rb_fantasia2))
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_copias1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(modifLayout.createSequentialGroup()
                                .addComponent(rb_romance2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_accion2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_historia2)))))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        modifLayout.setVerticalGroup(
            modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(modifLayout.createSequentialGroup()
                        .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rb_6)
                    .addComponent(rb_7)
                    .addComponent(rb_8)
                    .addComponent(rb_9)
                    .addComponent(rb_10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_copias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(rb_fantasia2)
                    .addComponent(rb_romance2)
                    .addComponent(rb_accion2)
                    .addComponent(rb_historia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_valor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edicion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_autor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(modifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modifLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(modifLayout.createSequentialGroup()
                        .addComponent(dc_fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Mofidica.setText("Modificar");
        Mofidica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MofidicaMouseClicked(evt);
            }
        });
        Mofidica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MofidicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar);
        Modificar.setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modificar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Mofidica))
                    .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Modificar_libro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Mofidica)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Modifica.addTab("Modificar", Modificar);

        jButton9.setText("Agregar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jLabel12.setText("Numero de copias");

        tf_copias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_copiasActionPerformed(evt);
            }
        });

        jLabel13.setText("Titulo");

        jLabel14.setText("Genero");

        tf_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tituloActionPerformed(evt);
            }
        });

        rgb_genero1.add(rb_fantasia1);
        rb_fantasia1.setText("Fantasia");

        jLabel15.setText("Descripcion");

        rgb_genero1.add(rb_romance1);
        rb_romance1.setText("Romance");

        rgb_genero1.add(rb_accion1);
        rb_accion1.setText("Accion");

        rgb_genero1.add(rb_historia1);
        rb_historia1.setText("Historia");

        jLabel16.setText("Valor");

        jLabel17.setText("Puntaje");

        jLabel18.setText("Edicion");

        rgb_puntaje.add(rb_1);
        rb_1.setText("1");

        rgb_puntaje.add(rb_2);
        rb_2.setText("2");

        rgb_puntaje.add(rb_3);
        rb_3.setText("3");

        jLabel19.setText("Autor");

        rgb_puntaje.add(rb_4);
        rb_4.setText("4");

        jLabel20.setText("Fecha de publicacion");

        rgb_puntaje.add(rb_5);
        rb_5.setText("5");

        javax.swing.GroupLayout IngresarLayout = new javax.swing.GroupLayout(Ingresar);
        Ingresar.setLayout(IngresarLayout);
        IngresarLayout.setHorizontalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_titulo)
                            .addComponent(tf_descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_5))
                    .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IngresarLayout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IngresarLayout.createSequentialGroup()
                            .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_autor)
                                .addComponent(tf_edicion))))
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9)
                            .addComponent(dc_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IngresarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(rb_fantasia1))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_copias, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IngresarLayout.createSequentialGroup()
                                .addComponent(rb_romance1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_accion1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_historia1)))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        IngresarLayout.setVerticalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rb_1)
                    .addComponent(rb_2)
                    .addComponent(rb_3)
                    .addComponent(rb_4)
                    .addComponent(rb_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rb_fantasia1)
                    .addComponent(rb_romance1)
                    .addComponent(rb_accion1)
                    .addComponent(rb_historia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addContainerGap())
                    .addGroup(IngresarLayout.createSequentialGroup()
                        .addComponent(dc_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9))))
        );

        Modifica.addTab("Ingresar Libro", Ingresar);

        jLabel30.setText("Escoja el libro a eliminar");

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BorraLayout = new javax.swing.GroupLayout(Borra);
        Borra.setLayout(BorraLayout);
        BorraLayout.setHorizontalGroup(
            BorraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorraLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(BorraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addGroup(BorraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Eliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        BorraLayout.setVerticalGroup(
            BorraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorraLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        Modifica.addTab("Borrar", Borra);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Modifica)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Modifica)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked

        user = tf_user.getText();

        password = pf_contrase.getText();

        int cont = 0;
        boolean login = false;
        boolean admin = false;
        for (Usuario u : lista) {
            if (u.getUsuario().equals(user) && u.getContrase().equals(password)) {
                login = true;

                usuario = cont;
            }
            cont++;
        }
        if (user.equals(administ) && password.equals(passwr)) {
            admin = true;
            Modificar.setEnabled(false);
            Modificar.setVisible(false);
        } else if (login) {
            tf_user.setText("");
            pf_contrase.setText("");
            c = lista.get(usuario);
            ArrayList<Libro> li = c.getLibros();
            for (Libro libro : li) {
                Devolver.addItem(libro);
                if (c.getGenero().equals(libro.getGenero())) {
                    jl_suger.add(libro.getTitulo(), this);
                }
            }
            for (Libro l : libro) {
                if (l.getCopias() > 0) {
                    Agregar_libro.addItem(l.getTitulo());
                }
            }

        } else if (admin) {
            tf_user.setText("");
            pf_contrase.setText("");
            for (Libro libro1 : libro) {
                Modificar_libro.addItem(libro1);
                Eliminar.addItem(libro1);
            }
            Usuario.setVisible(true);
            Ingresar.setVisible(true);
            modif.setVisible(true);
            Ingresar.setEnabled(true);
            Ingresar.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            tf_user.setText("");
            pf_contrase.setText("");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loginMouseClicked

    private void pf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_contraseñaActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void bt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_crearMouseClicked
        try {
            String usuario = tf_usuario.getText();
            String password = pf_contraseña.getText();
            String numero = tf_numero.getText();
            String email = tf_email.getText();
            String nombre = tf_nombre.getText();
            String genero = "";
            String fecha = dc_fecha.getDate().toString();

            if (rb_accion.isSelected()) {
                genero = "Accion";
            } else if (rb_fantasia.isSelected()) {
                genero = "Fantasia";
            } else if (rb_historia.isSelected()) {
                genero = "Historia";
            } else {
                genero = "Romance";
            }
            lista.add(new Usuario(usuario, nombre, fecha, numero, email, nombre, genero));
            usuario = "";
            password = "";
            numero = "";
            email = "";
            nombre = "";
            genero = "";
            fecha = "";
            tf_usuario.setText("");
            pf_contraseña.setText("");
            tf_numero.setText("");
            tf_email.setText("");
            dc_fecha.setDate(new Date());
            tf_nombre.setText("");
            JOptionPane.showMessageDialog(this, "Se creo el nuevo usuario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " No se pudo crear el nuevo usuario");

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_crearMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        try {
            String titulo = tf_titulo.getText();
            String descripcion = tf_descripcion.getText();
            String puntaje = " ";
            if (rb_1.isSelected()) {
                puntaje = "1";
            }
            if (rb_2.isSelected()) {
                puntaje = "2";
            }
            if (rb_3.isSelected()) {
                puntaje = "3";
            }
            if (rb_4.isSelected()) {
                puntaje = "4";
            }
            if (rb_5.isSelected()) {
                puntaje = "5";
            }
            Date fecha = dc_fecha.getDate();
            String edicion = tf_edicion.getText();
            String autor = tf_autor.getText();
            int copias = Integer.parseInt(tf_copias.getText());
            int valor = Integer.parseInt(tf_valor.getText());
            libro.add(new Libro(titulo, descripcion, puntaje, copias, fecha, valor, edicion));
            // jc_libro.addItem(libro.get(contl).toString());
            Modificar_libro.addItem(new Libro(titulo, descripcion, puntaje, copias, fecha, valor, edicion));
            Eliminar.addItem(new Libro(titulo, descripcion, puntaje, copias, fecha, valor, edicion));
            tf_autor.setText("");
            tf_copias.setText("");
            tf_descripcion.setText("");
            tf_titulo.setText("");
            dc_fecha.setDate(new Date());
            tf_edicion.setText("");
            tf_valor.setText("");
            titulo = "";
            descripcion = "";
            puntaje = "";
            fecha = new Date();
            autor = "";
            JOptionPane.showMessageDialog(this, " Se pudo guardar el nuevo libro");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " No se pudo guardar el nuevo libro");
            tf_autor.setText("");
            tf_copias.setText("");
            tf_descripcion.setText("");
            tf_titulo.setText("");
            dc_fecha.setDate(new Date());
            tf_edicion.setText("");
            tf_valor.setText("");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void tf_copiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_copiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_copiasActionPerformed

    private void tf_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tituloActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        int index = Agregar_libro.getSelectedIndex();
        c.getLibros().add(libro.get(index));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void MofidicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MofidicaMouseClicked
        int inde = Modificar_libro.getSelectedIndex();
        int puntaj = 0;
        String titulo = tf_titulo1.getText();
        String descripcion = tf_descripcion1.getText();
        String genero = "";
        if (rb_6.isSelected()) {
            puntaj = 1;
        }
        if (rb_7.isSelected()) {
            puntaj = 2;
        }
        if (rb_8.isSelected()) {
            puntaj = 3;
        }
        if (rb_9.isSelected()) {
            puntaj = 4;
        }
        if (rb_10.isSelected()) {
            puntaj = 5;
        }
        int copias = Integer.parseInt(tf_copias1.getText());
        if (rb_fantasia2.isSelected()) {
            genero = "fantasia";
        }
        if (rb_historia2.isSelected()) {
            genero = "Historia";
        }
        if (rb_romance2.isSelected()) {
            genero = "Romance";
        }
        if (rb_accion2.isSelected()) {
            genero = "Accion";
        }
        int valor = Integer.parseInt(tf_valor1.getText());
        String edicion = tf_edicion1.getText();
        String autor = tf_autor1.getText();
        Date fecha = dc_fecha2.getDate();
        libro.set(inde, new Libro(titulo, descripcion, genero, puntaj, fecha, valor, edicion));

        // TODO add your handling code here:
    }//GEN-LAST:event_MofidicaMouseClicked

    private void tf_copias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_copias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_copias1ActionPerformed

    private void tf_titulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_titulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_titulo1ActionPerformed

    private void tf_edicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_edicion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_edicion1ActionPerformed

    private void MofidicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MofidicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MofidicaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int ind = Eliminar.getSelectedIndex();
        libro.remove(ind);
        Eliminar.removeAll();
        for (Libro l : libro) {
            Eliminar.addItem(l);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principa().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Agregar_amigo;
    private javax.swing.JComboBox<String> Agregar_libro;
    private javax.swing.JPanel Borra;
    private javax.swing.JComboBox<Libro> Devolver;
    private javax.swing.JComboBox<Libro> Eliminar;
    private javax.swing.JPanel Ingresar;
    private javax.swing.JTabbedPane Modifica;
    private javax.swing.JPanel Modificar;
    private javax.swing.JComboBox<Libro> Modificar_libro;
    private javax.swing.JButton Mofidica;
    private javax.swing.JPanel Usuario;
    private javax.swing.JButton bt_crear;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private com.toedter.calendar.JDateChooser dc_fecha1;
    private com.toedter.calendar.JDateChooser dc_fecha2;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JComboBox<String> informacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jl_suger;
    private javax.swing.JButton login;
    private javax.swing.JPanel modif;
    private javax.swing.JPasswordField pf_contrase;
    private javax.swing.JPasswordField pf_contraseña;
    private javax.swing.ButtonGroup puntae;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_10;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_6;
    private javax.swing.JRadioButton rb_7;
    private javax.swing.JRadioButton rb_8;
    private javax.swing.JRadioButton rb_9;
    private javax.swing.JRadioButton rb_accion;
    private javax.swing.JRadioButton rb_accion1;
    private javax.swing.JRadioButton rb_accion2;
    private javax.swing.JRadioButton rb_fantasia;
    private javax.swing.JRadioButton rb_fantasia1;
    private javax.swing.JRadioButton rb_fantasia2;
    private javax.swing.JRadioButton rb_historia;
    private javax.swing.JRadioButton rb_historia1;
    private javax.swing.JRadioButton rb_historia2;
    private javax.swing.JRadioButton rb_romance;
    private javax.swing.JRadioButton rb_romance1;
    private javax.swing.JRadioButton rb_romance2;
    private javax.swing.ButtonGroup rgb_genero;
    private javax.swing.ButtonGroup rgb_genero1;
    private javax.swing.ButtonGroup rgb_puntaje;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_autor1;
    private javax.swing.JTextField tf_copias;
    private javax.swing.JTextField tf_copias1;
    private javax.swing.JTextField tf_descripcion;
    private javax.swing.JTextField tf_descripcion1;
    private javax.swing.JTextField tf_edicion;
    private javax.swing.JTextField tf_edicion1;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_numero;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_titulo1;
    private javax.swing.JTextField tf_user;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_valor;
    private javax.swing.JTextField tf_valor1;
    // End of variables declaration//GEN-END:variables

}
